announce = false
debug = true
description = 'Freeroam City'
gamemode = 'freeroam'
host = '0.0.0.0'
language = 'en'
modules = [ 'js-module', 'csharp-module' ]
name = 'Lost Santos Free City (BETA) Powered By Kysta Devs'
players = 100
port = 7788
streamingDistance = 400
migrationDistance = 1500

resources = [
    'freeroam',
    'addon-map',
    'altv-os-login',
    'stat',
    'ParkedVehicleSpawner',
    'motel',
    'garage',
    'timer',
    'pmenu',
    'interface',
    'ammunation',
    'altv-os-nametags',
    'Peds',
    'blip',
    'LSC',
    'pointing',
    'property',
    'shop',
    'pdm',
    'vendings',
    'job',
    'weed',
    'repo',
    'races',
    'penegakhukum',
    'voice',
    'parkour',
    'robfleeca',
    'dispatch',
    'lester',
    'survival',
    'addon-map-zoom',
    'airport',
    'casino',
    'altv-sit',
    'ocnlamtmc17',
    'ocni422spe',
    'ocnetrongt18',
    'altv-os-chat',
    'altv-vchat',
]


[voice]
bitrate = 64000
